spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

#this is a bug that needs to be resolved
management:
  metrics:
    export:
      wavefront:
        apiToken: ""

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    config:
      enabled: false
    kubernetes:
      reload:
        strategy: restart_context
        enabled: true
      config:
        enabled: true
        name: petclinic-config
management:
  endpoint:
    restart:
      enabled: true
